#!/usr/bin/env python3
"""Compare two checkpoint evaluation results."""
import argparse
import json
from pathlib import Path


def load_eval_results(filepath: str | Path) -> dict:
    """Load evaluation results from JSON file."""
    with open(filepath, encoding="utf-8") as f:
        return json.load(f)


def compare_metrics(metrics1: dict, metrics2: dict) -> list:
    """Compare metrics between two evaluations."""
    comparisons = []
    
    all_keys = set(metrics1.keys()) | set(metrics2.keys())
    
    for key in sorted(all_keys):
        val1 = metrics1.get(key)
        val2 = metrics2.get(key)
        
        if val1 is not None and val2 is not None:
            diff = val2 - val1
            pct_change = (diff / val1 * 100) if val1 != 0 else 0
            comparisons.append({
                "metric": key,
                "value1": val1,
                "value2": val2,
                "diff": diff,
                "pct_change": pct_change,
            })
        elif val1 is not None:
            comparisons.append({
                "metric": key,
                "value1": val1,
                "value2": None,
                "diff": None,
                "pct_change": None,
            })
        elif val2 is not None:
            comparisons.append({
                "metric": key,
                "value1": None,
                "value2": val2,
                "diff": None,
                "pct_change": None,
            })
    
    return comparisons


def generate_comparison(json1_data: dict, json2_data: dict) -> str:
    """Generate comparison report."""
    checkpoint1 = json1_data.get("checkpoint", "unknown")
    checkpoint2 = json2_data.get("checkpoint", "unknown")
    
    lines = [
        "# Checkpoint Comparison",
        "",
        f"**Checkpoint 1**: `{checkpoint1}`",
        f"**Checkpoint 2**: `{checkpoint2}`",
        "",
        "---",
        "",
        "## Metrics Comparison",
        "",
        "| Metric | Checkpoint 1 | Checkpoint 2 | Difference | % Change |",
        "|--------|--------------|--------------|------------|----------|",
    ]
    
    # Compare quantitative metrics
    metrics1 = json1_data.get("metrics", {})
    metrics2 = json2_data.get("metrics", {})
    comparisons = compare_metrics(metrics1, metrics2)
    
    for comp in comparisons:
        if comp["diff"] is not None:
            diff_str = f"{comp['diff']:+.4f}"
            pct_str = f"{comp['pct_change']:+.2f}%"
            # Better metrics (lower perplexity/loss) get green indicator
            indicator = "↓" if comp["metric"] in ("perplexity", "loss") and comp["diff"] < 0 else ""
            lines.append(
                f"| {comp['metric']} | {comp['value1']:.4f} | {comp['value2']:.4f} | "
                f"{diff_str} {indicator} | {pct_str} |"
            )
        else:
            val1_str = f"{comp['value1']:.4f}" if comp['value1'] is not None else "N/A"
            val2_str = f"{comp['value2']:.4f}" if comp['value2'] is not None else "N/A"
            lines.append(f"| {comp['metric']} | {val1_str} | {val2_str} | N/A | N/A |")
    
    # Compare QA metrics
    qa1 = json1_data.get("qa", {})
    qa2 = json2_data.get("qa", {})
    
    if qa1 or qa2:
        lines.extend(["", "---", "", "## QA Comparison", ""])
        
        if "coherence" in qa1 or "coherence" in qa2:
            c1 = qa1.get("coherence", {})
            c2 = qa2.get("coherence", {})
            lines.extend([
                "### Coherence",
                "",
                f"- Checkpoint 1: {c1.get('average_coherence', 'N/A')}",
                f"- Checkpoint 2: {c2.get('average_coherence', 'N/A')}",
                "",
            ])
        
        if "niah" in qa1 or "niah" in qa2:
            n1 = qa1.get("niah", {})
            n2 = qa2.get("niah", {})
            lines.extend([
                "### NIAH",
                "",
                f"- Checkpoint 1 accuracy: {n1.get('accuracy', 'N/A')}",
                f"- Checkpoint 2 accuracy: {n2.get('accuracy', 'N/A')}",
                "",
            ])
    
    lines.extend([
        "",
        "---",
        "",
        "*Comparison generated by M0.1 Evaluation Suite*",
    ])
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(
        description="Compare two checkpoint evaluation JSON files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/compare.py --json1 eval1.json --json2 eval2.json
  python scripts/compare.py --json1 eval1.json --json2 eval2.json --output comparison.md
        """
    )
    parser.add_argument("--json1", required=True, help="First evaluation JSON file")
    parser.add_argument("--json2", required=True, help="Second evaluation JSON file")
    parser.add_argument("--output", "-o", help="Output Markdown file (default: stdout)")
    
    args = parser.parse_args()
    
    json1_path = Path(args.json1)
    json2_path = Path(args.json2)
    
    if not json1_path.exists():
        print(f"Error: File not found: {json1_path}", file=__import__('sys').stderr)
        return 1
    if not json2_path.exists():
        print(f"Error: File not found: {json2_path}", file=__import__('sys').stderr)
        return 1
    
    data1 = load_eval_results(json1_path)
    data2 = load_eval_results(json2_path)
    
    report = generate_comparison(data1, data2)
    
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(report, encoding="utf-8")
        print(f"Comparison written to {output_path}")
    else:
        print(report)
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())