#!/usr/bin/env python3
"""Generate Markdown report from evaluation results."""
import argparse
import json
from datetime import datetime
from pathlib import Path


def load_eval_results(filepath: str | Path) -> dict:
    """Load evaluation results from JSON file."""
    with open(filepath, encoding="utf-8") as f:
        return json.load(f)


def format_metric(name: str, value: float, precision: int = 4) -> str:
    """Format a metric for the report."""
    return f"| {name} | {value:.{precision}f} |"


def generate_report(eval_data: dict) -> str:
    """Generate Markdown report from evaluation data."""
    timestamp = eval_data.get("timestamp", "unknown")
    checkpoint = eval_data.get("checkpoint", "unknown")
    
    report_lines = [
        "# Evaluation Report",
        "",
        f"**Generated**: {timestamp}",
        f"**Checkpoint**: `{checkpoint}`",
        "",
        "---",
        "",
        "## Quantitative Metrics",
        "",
        "| Metric | Value |",
        "|--------|-------|",
    ]
    
    metrics = eval_data.get("metrics", {})
    if "perplexity" in metrics:
        report_lines.append(format_metric("Perplexity", metrics["perplexity"]))
    if "loss" in metrics:
        report_lines.append(format_metric("Loss", metrics["loss"]))
    
    report_lines.extend(["", "---", "", "## Qualitative Benchmarks", ""])
    
    qa = eval_data.get("qa", {})
    if "coherence" in qa:
        coherence = qa["coherence"]
        report_lines.extend([
            "### Coherence Test",
            "",
            f"- **Average Coherence**: {coherence.get('average_coherence', 'N/A')}",
            f"- **Interval**: {coherence.get('interval', 128)} tokens",
            "",
        ])
    
    if "niah" in qa:
        niah = qa["niah"]
        report_lines.extend([
            "### Needle in a Haystack (NIAH)",
            "",
            f"- **Needle**: `{niah.get('needle', 'N/A')}`",
            f"- **Accuracy**: {niah.get('accuracy', 0):.4f}",
            f"- **Context Length**: {niah.get('context_length', 512)} tokens",
            "",
        ])
    
    report_lines.extend([
        "---",
        "",
        "## Summary",
        "",
        "Evaluation completed successfully." if metrics or qa else "No evaluation data available.",
        "",
        f"*Report generated by M0.1 Evaluation Suite on {datetime.utcnow().isoformat()}Z*",
    ])
    
    return "\n".join(report_lines)


def main():
    parser = argparse.ArgumentParser(
        description="Generate Markdown report from evaluation JSON",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python scripts/generate_report.py --eval artifacts/evals/results_20260718.json
  python scripts/generate_report.py --eval results.json --output report.md
        """
    )
    parser.add_argument("--eval", required=True, help="Path to evaluation JSON file")
    parser.add_argument("--output", "-o", help="Output Markdown file (default: stdout)")
    
    args = parser.parse_args()
    
    eval_path = Path(args.eval)
    if not eval_path.exists():
        print(f"Error: Evaluation file not found: {eval_path}", file=__import__('sys').stderr)
        return 1
    
    eval_data = load_eval_results(eval_path)
    report = generate_report(eval_data)
    
    if args.output:
        output_path = Path(args.output)
        output_path.write_text(report, encoding="utf-8")
        print(f"Report written to {output_path}")
    else:
        print(report)
    
    return 0


if __name__ == "__main__":
    raise SystemExit(main())